
  create table "public"."Constelacao" (
    "idConstelacao" bigint generated by default as identity not null,
    "nome" text not null,
    "descricao" text
      );


alter table "public"."Constelacao" enable row level security;


  create table "public"."CorpoCeleste" (
    "idCorpoCeleste" bigint generated by default as identity not null,
    "nome" text not null,
    "descricao" text,
    "tipo" text not null,
    "distancia" numeric
      );


alter table "public"."CorpoCeleste" enable row level security;


  create table "public"."DadoMetorologico" (
    "idDadoMeteorologico" bigint generated by default as identity not null,
    "dir_vento" double precision not null,
    "vel_vento" double precision not null,
    "dataHora" timestamp with time zone not null,
    "temperatura" double precision not null,
    "indive_UV" integer not null,
    "umidade" double precision not null
      );


alter table "public"."DadoMetorologico" enable row level security;


  create table "public"."MaterialEstudo" (
    "idMaterialEstudo" bigint generated by default as identity not null,
    "tipo" text not null,
    "data_publicacao" timestamp with time zone not null,
    "arquivo" text not null,
    "autor" text[] not null,
    "descricao" text,
    "titulo" text not null
      );


alter table "public"."MaterialEstudo" enable row level security;


  create table "public"."MissaoEspacial" (
    "id" bigint generated by default as identity not null,
    "nome" text not null,
    "descricao" text,
    "status" text not null,
    "agencia" text not null,
    "dataLancamento" timestamp with time zone not null
      );


alter table "public"."MissaoEspacial" enable row level security;


  create table "public"."Pesquisador" (
    "idPesquisador" bigint not null,
    "tipo" text
      );


alter table "public"."Pesquisador" enable row level security;


  create table "public"."PontoObservacao" (
    "idPontoObs" bigint generated by default as identity not null,
    "latitude" numeric not null,
    "longitude" numeric not null,
    "descricao" text,
    "nome" text not null
      );


alter table "public"."PontoObservacao" enable row level security;

create type tipo_acesso as enum ('admin', 'pesquisador', 'visitante');

  create table "public"."Usuario" (
    id uuid primary key references auth.users(id) on delete cascade
    "senha" text not null,
    "username" text not null,
    "tipo_acesso" tipo_acesso not null default 'visitante',
    "email" text not null,
    "nome" text not null
      );


alter table "public"."Usuario" enable row level security;

CREATE UNIQUE INDEX "Constelacao_nome_key" ON public."Constelacao" USING btree (nome);

CREATE UNIQUE INDEX "Constelacao_pkey" ON public."Constelacao" USING btree ("idConstelacao");

CREATE UNIQUE INDEX "CorpoCeleste_nome_key" ON public."CorpoCeleste" USING btree (nome);

CREATE UNIQUE INDEX "CorpoCeleste_pkey" ON public."CorpoCeleste" USING btree ("idCorpoCeleste");

CREATE UNIQUE INDEX "DadoMetorologico_pkey" ON public."DadoMetorologico" USING btree ("idDadoMeteorologico");

CREATE UNIQUE INDEX "MaterialEstudo_pkey" ON public."MaterialEstudo" USING btree ("idMaterialEstudo");

CREATE UNIQUE INDEX "MissaoEspacial_nome_key" ON public."MissaoEspacial" USING btree (nome);

CREATE UNIQUE INDEX "MissaoEspacial_pkey" ON public."MissaoEspacial" USING btree (id);

CREATE UNIQUE INDEX "Pesquisador_pkey" ON public."Pesquisador" USING btree ("idPesquisador");

CREATE UNIQUE INDEX "PontoObservacao_pkey" ON public."PontoObservacao" USING btree ("idPontoObs");

CREATE UNIQUE INDEX "Usuario_email_key" ON public."Usuario" USING btree (email);

CREATE UNIQUE INDEX "Usuario_pkey" ON public."Usuario" USING btree ("idUsuario");

CREATE UNIQUE INDEX "Usuario_username_key" ON public."Usuario" USING btree (username);

alter table "public"."Constelacao" add constraint "Constelacao_pkey" PRIMARY KEY using index "Constelacao_pkey";

alter table "public"."CorpoCeleste" add constraint "CorpoCeleste_pkey" PRIMARY KEY using index "CorpoCeleste_pkey";

alter table "public"."DadoMetorologico" add constraint "DadoMetorologico_pkey" PRIMARY KEY using index "DadoMetorologico_pkey";

alter table "public"."MaterialEstudo" add constraint "MaterialEstudo_pkey" PRIMARY KEY using index "MaterialEstudo_pkey";

alter table "public"."MissaoEspacial" add constraint "MissaoEspacial_pkey" PRIMARY KEY using index "MissaoEspacial_pkey";

alter table "public"."Pesquisador" add constraint "Pesquisador_pkey" PRIMARY KEY using index "Pesquisador_pkey";

alter table "public"."PontoObservacao" add constraint "PontoObservacao_pkey" PRIMARY KEY using index "PontoObservacao_pkey";

alter table "public"."Usuario" add constraint "Usuario_pkey" PRIMARY KEY using index "Usuario_pkey";

alter table "public"."Constelacao" add constraint "Constelacao_nome_key" UNIQUE using index "Constelacao_nome_key";

alter table "public"."CorpoCeleste" add constraint "CorpoCeleste_nome_key" UNIQUE using index "CorpoCeleste_nome_key";

alter table "public"."MissaoEspacial" add constraint "MissaoEspacial_nome_key" UNIQUE using index "MissaoEspacial_nome_key";

alter table "public"."Pesquisador" add constraint "Pesquisador_idPesquisador_fkey" FOREIGN KEY ("idPesquisador") REFERENCES public."Usuario"("idUsuario") not valid;

alter table "public"."Pesquisador" validate constraint "Pesquisador_idPesquisador_fkey";

alter table "public"."Usuario" add constraint "Usuario_email_key" UNIQUE using index "Usuario_email_key";

alter table "public"."Usuario" add constraint "Usuario_username_key" UNIQUE using index "Usuario_username_key";

grant delete on table "public"."Constelacao" to "anon";

grant insert on table "public"."Constelacao" to "anon";

grant references on table "public"."Constelacao" to "anon";

grant select on table "public"."Constelacao" to "anon";

grant trigger on table "public"."Constelacao" to "anon";

grant truncate on table "public"."Constelacao" to "anon";

grant update on table "public"."Constelacao" to "anon";

grant delete on table "public"."Constelacao" to "authenticated";

grant insert on table "public"."Constelacao" to "authenticated";

grant references on table "public"."Constelacao" to "authenticated";

grant select on table "public"."Constelacao" to "authenticated";

grant trigger on table "public"."Constelacao" to "authenticated";

grant truncate on table "public"."Constelacao" to "authenticated";

grant update on table "public"."Constelacao" to "authenticated";

grant delete on table "public"."Constelacao" to "service_role";

grant insert on table "public"."Constelacao" to "service_role";

grant references on table "public"."Constelacao" to "service_role";

grant select on table "public"."Constelacao" to "service_role";

grant trigger on table "public"."Constelacao" to "service_role";

grant truncate on table "public"."Constelacao" to "service_role";

grant update on table "public"."Constelacao" to "service_role";

grant delete on table "public"."CorpoCeleste" to "anon";

grant insert on table "public"."CorpoCeleste" to "anon";

grant references on table "public"."CorpoCeleste" to "anon";

grant select on table "public"."CorpoCeleste" to "anon";

grant trigger on table "public"."CorpoCeleste" to "anon";

grant truncate on table "public"."CorpoCeleste" to "anon";

grant update on table "public"."CorpoCeleste" to "anon";

grant delete on table "public"."CorpoCeleste" to "authenticated";

grant insert on table "public"."CorpoCeleste" to "authenticated";

grant references on table "public"."CorpoCeleste" to "authenticated";

grant select on table "public"."CorpoCeleste" to "authenticated";

grant trigger on table "public"."CorpoCeleste" to "authenticated";

grant truncate on table "public"."CorpoCeleste" to "authenticated";

grant update on table "public"."CorpoCeleste" to "authenticated";

grant delete on table "public"."CorpoCeleste" to "service_role";

grant insert on table "public"."CorpoCeleste" to "service_role";

grant references on table "public"."CorpoCeleste" to "service_role";

grant select on table "public"."CorpoCeleste" to "service_role";

grant trigger on table "public"."CorpoCeleste" to "service_role";

grant truncate on table "public"."CorpoCeleste" to "service_role";

grant update on table "public"."CorpoCeleste" to "service_role";

grant delete on table "public"."DadoMetorologico" to "anon";

grant insert on table "public"."DadoMetorologico" to "anon";

grant references on table "public"."DadoMetorologico" to "anon";

grant select on table "public"."DadoMetorologico" to "anon";

grant trigger on table "public"."DadoMetorologico" to "anon";

grant truncate on table "public"."DadoMetorologico" to "anon";

grant update on table "public"."DadoMetorologico" to "anon";

grant delete on table "public"."DadoMetorologico" to "authenticated";

grant insert on table "public"."DadoMetorologico" to "authenticated";

grant references on table "public"."DadoMetorologico" to "authenticated";

grant select on table "public"."DadoMetorologico" to "authenticated";

grant trigger on table "public"."DadoMetorologico" to "authenticated";

grant truncate on table "public"."DadoMetorologico" to "authenticated";

grant update on table "public"."DadoMetorologico" to "authenticated";

grant delete on table "public"."DadoMetorologico" to "service_role";

grant insert on table "public"."DadoMetorologico" to "service_role";

grant references on table "public"."DadoMetorologico" to "service_role";

grant select on table "public"."DadoMetorologico" to "service_role";

grant trigger on table "public"."DadoMetorologico" to "service_role";

grant truncate on table "public"."DadoMetorologico" to "service_role";

grant update on table "public"."DadoMetorologico" to "service_role";

grant delete on table "public"."MaterialEstudo" to "anon";

grant insert on table "public"."MaterialEstudo" to "anon";

grant references on table "public"."MaterialEstudo" to "anon";

grant select on table "public"."MaterialEstudo" to "anon";

grant trigger on table "public"."MaterialEstudo" to "anon";

grant truncate on table "public"."MaterialEstudo" to "anon";

grant update on table "public"."MaterialEstudo" to "anon";

grant delete on table "public"."MaterialEstudo" to "authenticated";

grant insert on table "public"."MaterialEstudo" to "authenticated";

grant references on table "public"."MaterialEstudo" to "authenticated";

grant select on table "public"."MaterialEstudo" to "authenticated";

grant trigger on table "public"."MaterialEstudo" to "authenticated";

grant truncate on table "public"."MaterialEstudo" to "authenticated";

grant update on table "public"."MaterialEstudo" to "authenticated";

grant delete on table "public"."MaterialEstudo" to "service_role";

grant insert on table "public"."MaterialEstudo" to "service_role";

grant references on table "public"."MaterialEstudo" to "service_role";

grant select on table "public"."MaterialEstudo" to "service_role";

grant trigger on table "public"."MaterialEstudo" to "service_role";

grant truncate on table "public"."MaterialEstudo" to "service_role";

grant update on table "public"."MaterialEstudo" to "service_role";

grant delete on table "public"."MissaoEspacial" to "anon";

grant insert on table "public"."MissaoEspacial" to "anon";

grant references on table "public"."MissaoEspacial" to "anon";

grant select on table "public"."MissaoEspacial" to "anon";

grant trigger on table "public"."MissaoEspacial" to "anon";

grant truncate on table "public"."MissaoEspacial" to "anon";

grant update on table "public"."MissaoEspacial" to "anon";

grant delete on table "public"."MissaoEspacial" to "authenticated";

grant insert on table "public"."MissaoEspacial" to "authenticated";

grant references on table "public"."MissaoEspacial" to "authenticated";

grant select on table "public"."MissaoEspacial" to "authenticated";

grant trigger on table "public"."MissaoEspacial" to "authenticated";

grant truncate on table "public"."MissaoEspacial" to "authenticated";

grant update on table "public"."MissaoEspacial" to "authenticated";

grant delete on table "public"."MissaoEspacial" to "service_role";

grant insert on table "public"."MissaoEspacial" to "service_role";

grant references on table "public"."MissaoEspacial" to "service_role";

grant select on table "public"."MissaoEspacial" to "service_role";

grant trigger on table "public"."MissaoEspacial" to "service_role";

grant truncate on table "public"."MissaoEspacial" to "service_role";

grant update on table "public"."MissaoEspacial" to "service_role";

grant delete on table "public"."Pesquisador" to "anon";

grant insert on table "public"."Pesquisador" to "anon";

grant references on table "public"."Pesquisador" to "anon";

grant select on table "public"."Pesquisador" to "anon";

grant trigger on table "public"."Pesquisador" to "anon";

grant truncate on table "public"."Pesquisador" to "anon";

grant update on table "public"."Pesquisador" to "anon";

grant delete on table "public"."Pesquisador" to "authenticated";

grant insert on table "public"."Pesquisador" to "authenticated";

grant references on table "public"."Pesquisador" to "authenticated";

grant select on table "public"."Pesquisador" to "authenticated";

grant trigger on table "public"."Pesquisador" to "authenticated";

grant truncate on table "public"."Pesquisador" to "authenticated";

grant update on table "public"."Pesquisador" to "authenticated";

grant delete on table "public"."Pesquisador" to "service_role";

grant insert on table "public"."Pesquisador" to "service_role";

grant references on table "public"."Pesquisador" to "service_role";

grant select on table "public"."Pesquisador" to "service_role";

grant trigger on table "public"."Pesquisador" to "service_role";

grant truncate on table "public"."Pesquisador" to "service_role";

grant update on table "public"."Pesquisador" to "service_role";

grant delete on table "public"."PontoObservacao" to "anon";

grant insert on table "public"."PontoObservacao" to "anon";

grant references on table "public"."PontoObservacao" to "anon";

grant select on table "public"."PontoObservacao" to "anon";

grant trigger on table "public"."PontoObservacao" to "anon";

grant truncate on table "public"."PontoObservacao" to "anon";

grant update on table "public"."PontoObservacao" to "anon";

grant delete on table "public"."PontoObservacao" to "authenticated";

grant insert on table "public"."PontoObservacao" to "authenticated";

grant references on table "public"."PontoObservacao" to "authenticated";

grant select on table "public"."PontoObservacao" to "authenticated";

grant trigger on table "public"."PontoObservacao" to "authenticated";

grant truncate on table "public"."PontoObservacao" to "authenticated";

grant update on table "public"."PontoObservacao" to "authenticated";

grant delete on table "public"."PontoObservacao" to "service_role";

grant insert on table "public"."PontoObservacao" to "service_role";

grant references on table "public"."PontoObservacao" to "service_role";

grant select on table "public"."PontoObservacao" to "service_role";

grant trigger on table "public"."PontoObservacao" to "service_role";

grant truncate on table "public"."PontoObservacao" to "service_role";

grant update on table "public"."PontoObservacao" to "service_role";

grant delete on table "public"."Usuario" to "anon";

grant insert on table "public"."Usuario" to "anon";

grant references on table "public"."Usuario" to "anon";

grant select on table "public"."Usuario" to "anon";

grant trigger on table "public"."Usuario" to "anon";

grant truncate on table "public"."Usuario" to "anon";

grant update on table "public"."Usuario" to "anon";

grant delete on table "public"."Usuario" to "authenticated";

grant insert on table "public"."Usuario" to "authenticated";

grant references on table "public"."Usuario" to "authenticated";

grant select on table "public"."Usuario" to "authenticated";

grant trigger on table "public"."Usuario" to "authenticated";

grant truncate on table "public"."Usuario" to "authenticated";

grant update on table "public"."Usuario" to "authenticated";

grant delete on table "public"."Usuario" to "service_role";

grant insert on table "public"."Usuario" to "service_role";

grant references on table "public"."Usuario" to "service_role";

grant select on table "public"."Usuario" to "service_role";

grant trigger on table "public"."Usuario" to "service_role";

grant truncate on table "public"."Usuario" to "service_role";

grant update on table "public"."Usuario" to "service_role";


